# Generated by Django 3.2.20 on 2023-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(choices=[('Stock', 'Stock'), ('Delivery', 'Delivery'), ('Feedback', 'Feedback'), ('Other', 'Other')], default='Other', max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('on_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
